  agent:
    label: master
  tools:
    maven: maven
  stages:
    - stage: BuildJava
          steps:
        - srcMavenCleanPackage()
    - stage: Test
          steps:
          - srcMavenTest()
    - stage: DockerBuild
    steps:
        - srcDockerBuild()


