  stages:
    - stage: BuildJava
          steps:
        - srcCheckout()
        - srcMavenCleanPackage()
    - stage: Test
          steps:
          - srcMavenTest()
    - stage: DockerBuild
    steps:
        - srcDockerBuild()


